apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: adamhoover-adamhoover-poi-map-app-dev
  annotations:
    argocd/app-name: adamhoover-adamhoover-poi-map-app-dev
    backstage.io/kubernetes-id: adamhoover-adamhoover-poi-map-app-dev
    backstage.io/kubernetes-namespace: adamhoover
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/instance=adamhoover-adamhoover-poi-map-app-dev'
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: Summit23Janus2/adamhoover-frontend
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - typescript
    - angular
    - workshop
  links:
    - url: https://console-openshift-console.apps.summit23blues.6mbu.p1.openshiftapps.com/dev-pipelines/ns/adamhoover/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.summit23blues.6mbu.p1.openshiftapps.com/k8s/ns/adamhoover/deployments/adamhoover-poi-map-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.summit23blues.6mbu.p1.openshiftapps.com/#https://github.com/Summit23Janus2/adamhoover-frontend?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
    - url: http://adamhoover-poi-map-app-adamhoover.apps.summit23blues.6mbu.p1.openshiftapps.com
      title: Map
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "adamhoover"
  system: workshop-system-adamhoover
  consumesApis:
    - gateway-api-adamhoover
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-adamhoover
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "adamhoover"
